example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
from django.urls import path
from katalog.views import show_catalog

app_name = 'katalog'

urlpatterns = [
    path('', show_catalog, name='show_catalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_watchlist, show_html, show_xml, show_json

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_watchlist, name='show_watchlist'),
    path('html/', show_html, name='show_html'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import delete_ajax, login_user, register, show_json, show_todolist, logout_user, create_task, delete_task, change_status, show_todolist_ajax
from todolist.views import add_task_ajax

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist_ajax, name='show_todolist_ajax'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create-task'),
    path('delete/<int:id>', delete_ajax, name='delete'),
    path('change/<int:id>', change_status, name='change'),
    path('json/', show_json, name='show-json'),
    path('add/', add_task_ajax, name='add-task-ajax'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class MyWatchList(models.Model):
    watched = models.BooleanField()
    title = models.TextField()
    rating = models.IntegerField()
    release_date = models.DateField()
    review = models.TextField()

todolist/models.py
from statistics import mode
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    title = models.CharField(max_length=300)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

def show_catalog(request):
    data_catalog_item = CatalogItem.objects.all()
    context = {
        'list_item': data_catalog_item,
        'nama': 'Jaycent Gunawan Ongris',
        'npm': '2106750231'
    }
    
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchList
from django.http import HttpResponse
from django.core import serializers

def show_watchlist(request):
    return render(request, "empty.html")

def show_html(request):
    watchlist_data = MyWatchList.objects.all()
    watched, not_watched = 0, 0
    for movie in watchlist_data:
        if movie.watched:
            watched += 1
        else:
            not_watched += 1

    context = {
        'list_watchlist': watchlist_data,
        'watched': watched,
        'not_watched': not_watched
    }
    return render(request, "watchlist.html", context)

def show_xml(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from todolist.models import Task
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.core import serializers

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    task_data = Task.objects.filter(user = request.user)
    context = {
        'task_list': task_data,
        'username': request.user,
    }
    return render(request, "todolist.html", context)

# Create your views here.
def register(request):
    form = UserCreationForm()
    
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully created an account')
            return redirect('todolist:login')
    
    context = {'form': form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('todolist:show_todolist_ajax')
        else:
            messages.info(request, 'Username or password is wrong')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return redirect('todolist:login')

@login_required(login_url='/todolist/login/')
def create_task(request):
    if request.method == 'POST':
        # request.user refers to current logged-in user
        user = request.user
        # request.POST.get akan mengembalikan None jika 'taskname' tidak ada pada request.POST
        title = request.POST.get('taskname')
        description = request.POST.get('taskdesc')
        task = Task.objects.create(user=user, title=title, description=description)
        messages.success(request, "Successfully add new task")
        return redirect('todolist:show_todolist')
    context = {}
    return render(request, 'new_task.html', context)

@login_required(login_url='/todolist/login/')
def delete_task(request, id):
    task = Task.objects.get(id=id)
    if task.user == request.user:
        task.delete()
    else:
        messages.info(request, "You can't delete this task")
    return redirect('todolist:show_todolist_ajax')

@login_required(login_url='/todolist/login/')
def change_status(request, id):
    task = Task.objects.get(id=id)
    if task.user == request.user:
        task.is_finished = not task.is_finished
        task.save()
    else:
        messages.info(request, "You can't change the status of this task")
    return redirect('todolist:show_todolist_ajax')

@login_required(login_url='/todolist/login/')
def show_json(request):
    data = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/todolist/login/')
def show_todolist_ajax(request):
    context = {
        'username': request.user,
    }
    return render(request, "todolist.html", context)

@login_required(login_url='/todolist/login/')
def add_task_ajax(request):
    if request.POST.get('action') == 'post':
        user = request.user
        # dari data yang ada pada jQuery
        title = request.POST.get('title')
        description = request.POST.get('description')

        Task.objects.create(user=user, title=title, description=description)
        return JsonResponse({'status':'Task is added successfully'})
    else:
        return JsonResponse({'status': 'Invalid request'}, status=400)

@login_required(login_url='/todolist/login/')
def delete_ajax(request, id):
    task = Task.objects.get(id=id)
    if task.user == request.user:
        task.delete()
        return JsonResponse({'status': 'Task is deleted successfully'})
    else:
        messages.info(request, "You can't delete this task")
        return JsonResponse({'status': 'Invalid deletion'}, status=403)
    

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Comforter+Brush&display=swap" rel="stylesheet">
  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in list_item %}
    <tr>
        <th>{{item.item_name}}</th>
        <th>{{item.item_price}}</th>
        <th>{{item.item_stock}}</th>
        <th>{{item.rating}}</th>
        <th>{{item.description}}</th>
        <th>{{item.item_url}}</th>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/watchlist.html
{% extends 'base.html' %}

 {% block content %}
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Comforter+Brush&display=swap" rel="stylesheet">
  <h1>Lab 2 Assignment PBP/PBD</h1>

  <table style="margin-left: auto; margin-right: auto;">
    <tr>
      <th style="padding: 5px;">Watched</th>
      <th style="padding: 5px;">Title</th>
      <th style="padding: 5px;">Rating</th>
      <th style="padding: 5px;">Release Date</th>
      <th style="padding: 5px;">Review</th>
    </tr>


    {% comment %} Add the data below this line {% endcomment %}
    {% for movie in list_watchlist %}
    <tr>
        <th style="font-weight: normal;">{{movie.watched}}</th>
        <th style="font-weight: normal;">{{movie.title}}</th>
        <th style="font-weight: normal;">{{movie.rating}}</th>
        <th style="font-weight: normal;">{{movie.release_date}}</th>
        <th style="font-weight: normal;">{{movie.review}}</th>
    </tr>
    {% endfor %}
    </table>
    
    {% if watched >= not_watched %}
    <h3 style="text-align: center;">Selamat, kamu sudah banyak menonton!</h3>
    {% else %}
    <h3 style="text-align: center;">Wah, kamu masih sedikit menonton!</h3>
    {% endif %}

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
{% load static %}
<link rel="stylesheet" href="{% static 'css\login.css' %}">
{% endblock meta %}

{% block content %}
<body>
    <div class="container p-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-xl-5">
                <div class="card bg-white text-dark shadow-lg border-0" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <div class = "login">
                            <h1 class="title">Welcome Back!</h1>
                                <p class="h6 text-secondary p-0" style="font-weight: normal;">Please log in to use the application</h4>
                                    <form method="POST" action="">
                                        {% csrf_token %}
                                        <div class="form-floating">
                                            <input type="text" name="username" placeholder="Username" class="form-control my-3">
                                            <label for="floatingInputValue">Username</label>
                                        </div>
                                        <div class="form-floating">
                                            <input type="password" name="password" placeholder="Password" class="form-control my-3">
                                            <label for="floatingInputValue">Password</label>
                                        </div>
                                        
                                        <input class="btn login_btn btn-primary mx-auto m-1" type="submit" value="Login">     
                                    </form>
                                    {% if messages %}
                                        {% for message in messages %}
                                            <p class="h6 text-secondary p-1 mt-1 fw-normal">{{ message }}</p>
                                        {% endfor %}
                                    {% endif %}     
                                <p class="text-align-center mt-2">No account? <a href="{% url 'todolist:register' %}" class="text-decoration-none fw-bold">Create a new one</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock content %}

todolist/templates/new_task.html
{% extends 'base.html' %}

{% block meta %}
<title>New Task</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
{% endblock meta %}

{% block content %}
<body>
    <nav class="navbar navbar-expand-sm mb-3 p-2" style="background-color: #ADD8E6;">
        <div class="container-fluid">
          <span class="navbar-brand m-2 h-1 fw-bold">To-Do List</span>
          <ul class="navbar-nav ml-auto">
            <li class="navbar-text p-2 m-2 fw-bold">{{username}}</li>
            <li><a class="btn btn-danger m-2" href="{% url 'todolist:logout' %}" role="button">Logout</a></li>
          </ul>
        </div>
      </nav>
    <div class="text-center">
        <span class="h1 fw-bold">Create Your New Task</span>
        <form method="POST" action="">
            {% csrf_token %}
            <div class="m-3 p-1">
                <label for="exampleFormControlInput1" class="form-label h4">Task Name</label>
                <input type="text" name="taskname" class="form-control" id="exampleFormControlInput1" placeholder="Task Name" required>
            </div>
            <div class="m-3 p-1">
                <label for="exampleFormControlInput1" class="form-label h4">Task Description</label>
                <textarea name="taskdesc" class="form-control" id="exampleFormControlInput1" placeholder="Task Description" rows="5"></textarea>
            </div>
            <div class="row m-2">
                <input class="col btn btn-success m-2" type="submit" value="Save">
                <a class="col btn btn-danger m-2" href="/todolist/" role="button">Discard and Go Back</a>
              </div>
        </form>
    </div>
</body>
{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Account Registration</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
{% load static %}
<link rel="stylesheet" href="{% static 'css\login.css' %}">
{% endblock meta %}

{% block content %}
<body>
    <div class="container p-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-xl-8">
                <div class="card bg-white text-dark shadow-lg border-0" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <div class = "login">
                            <h1 class="title">Registration Form</h1>
                                    <form method="POST" action="">
                                        {% csrf_token %}
                                        <div class="table-responsive">
                                            <table class="table" style="border-color: white;">
                                                {{form.as_table}}
                                            </table>
                                        </div>
                                        <input class="btn btn-primary mx-auto mt-3" type="submit" value="Register" name="submit">     
                                    </form>
                                    {% if messages %}
                                        {% for message in messages %}
                                            <p>{{ message }}</p>
                                        {% endfor %}
                                    {% endif %}     
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<title>To-Do List</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

{% load static %}
<link rel="stylesheet" href="{% static 'css\todolist.css' %}">
{% endblock meta %}

{% block content %}
<body>
  <nav class="navbar navbar-expand-sm mb-3 p-2" style="background-color: #ADD8E6;">
    <div class="container-fluid">
      <span class="navbar-brand m-2 h-1 fw-bold">To-Do List</span>
      <ul class="navbar-nav ml-auto">
        <li class="navbar-text p-2 m-2 fw-bold">{{username}}</li>
        <li><button type="button" class="btn btn-primary m-2" data-bs-toggle="modal" data-bs-target="#create-new">Add Task</button></li>
        <li><a class="btn btn-danger m-2" href="{% url 'todolist:logout' %}" role="button">Logout</a></li>
      </ul>
    </div>
  </nav>
  <div class="modal fade" id="create-new" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Add New Task</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="clearFields()"></button>
        </div>
        <div class="modal-body">
          <form method="POST" action="" id="new-task">
            {% csrf_token %}
            <div class="m-3 p-1">
                <label for="exampleFormControlInput1" class="form-label h5">Task Name</label>
                <input type="text" name="taskname" class="form-control" id="taskname" placeholder="Task Name" required>
            </div>
            <div class="m-3 p-1">
                <label for="exampleFormControlInput1" class="form-label h5">Task Description</label>
                <textarea name="taskdesc" class="form-control" id="taskdesc" placeholder="Task Description" rows="5"></textarea>
            </div>
            <button type="button" class="btn btn-danger" data-bs-dismiss="modal" onclick="clearFields()">Discard</button>
            <button type="submit" class="btn btn-submit btn-primary">Save</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div id="task-cards"></div> 
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-primary alert-dismissible fade show mx-4" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}

  <script>
  function getData(){
    $.get('/todolist/json/', function(data){
      showData(data);
    })
  };

  function showData(data){
    if (data.length == 0){
      let msg = `<div class="msg text-center">
                  <div class="fw-bold h1">No Task :(</div>
                  <div class="fw-normal text-muted">Add your first task by clicking the "Add Task" button above</div>
                  </div>`;
      document.getElementById('task-cards').innerHTML = msg;
    } else{
      let card = '';
      for (let task of data){
        if (task.fields.is_finished){
          card += `<div class="card p-1 m-4 shadow-lg">
            <div class="card-body">
              <div class="title-status">
                <p class="card-title h4">${task.fields.title}</h4>
                  <span class="badge rounded-pill bg-success align-top">Finished</span>
              </div>
              <p class="card-text">${task.fields.description}</p>
              <p class="card-text"><small class="text-muted">Created on ${task.fields.date}</small></p>
            </div>
            <div class="row m-2">
              <a class="col btn btn-outline-primary m-2" href="change/${task.pk}" role="button">Change Status</a>
              <a class="col btn btn-outline-danger m-2 del-task" onclick="deleteData(${task.pk})" role="button">Delete Task</a>
            </div>
            </div>`;
        } else{
          card += `<div class="card p-1 m-4 shadow-lg">
            <div class="card-body">
              <div class="title-status">
                <p class="card-title h4">${task.fields.title}</h4>
                  <span class="badge rounded-pill bg-danger align-top">Not Finished</span>
              </div>
              <p class="card-text">${task.fields.description}</p>
              <p class="card-text"><small class="text-muted">Created on ${task.fields.date}</small></p>
            </div>
            <div class="row m-2">
              <a class="col btn btn-outline-primary m-2" href="change/${task.pk}" role="button">Change Status</a>
              <a class="col btn btn-outline-danger m-2 del-task" onclick="deleteData(${task.pk})" role="button">Delete Task</a>
            </div>
            </div>`;
        } 
      };
      document.getElementById('task-cards').innerHTML = card;
    };  
  };

  function clearFields(){
    $("#new-task")[0].reset();
  }

  function deleteData(id){
    $.ajax({
      type: 'DELETE',
      url: '/todolist/delete/' + id,
      dataType: 'json',
      headers: {
        "X-CSRFTOKEN": "{{ csrf_token }}"
      },
      success: function(data){
        console.log("Task is deleted successfully");
        getData();
      }
    })
  }

  $(document).ready(function(){
    getData();
    $("button").click(function (){
      getData();
    });
  });

  $(document).on('submit', '#new-task', function(e){
    e.preventDefault();
    $.ajax({
      type: 'POST',
      url: '/todolist/add/',
      data: {
        title: $('#taskname').val(),
        description: $('#taskdesc').val(),
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
        action:'post',
      },
      dataType: 'json',
      success: function(data){
        console.log("Task is created successfully");
        getData();
        $('#create-new').modal('hide');
        $('.modal-backdrop').remove();
        clearFields()
      }
    })
  })
</script>  
  </body>
 {% endblock content %}